name: MySQL Setup and Seed Data

on:
  push:
    branches:
      - main

jobs:
  mysql-setup:
    runs-on: ubuntu-latest

    steps:
    # 1. Klono repo-n e projektit
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Përditëso Ubuntu dhe instalo MySQL
    - name: Update Ubuntu and Install MySQL
      run: |
        sudo apt update -y
        sudo apt upgrade -y
        sudo apt install -y mysql-server mysql-client
        sudo systemctl start mysql
        sudo systemctl enable mysql

    # 3. Vendos password për root dhe krijo bazën e të dhënave
    - name: Set MySQL Root Password and Create Database
      run: |
        sudo mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'Moseprek12@';"
        sudo mysql -u root -e "FLUSH PRIVILEGES;"
        sudo mysql -u root -e "CREATE DATABASE IF NOT EXISTS my_database;"

    # 4. Ekzekuto SQL skriptet për krijimin e tabelave dhe futjen e të dhënave
    - name: Execute SQL Scripts
      run: |
        sudo mysql -u root -p'Moseprek12@' my_database < ./01-create-table.sql
        sudo mysql -u root -p'Moseprek12@' my_database < ./02-seed-data.sql

    # 5. Verifikimi i të dhënave
    - name: Verify Database Setup
      run: |
        sudo mysql -u root -p'Moseprek12@' -e "USE my_database; SELECT * FROM employees;"
