name: MySQL Setup, Create Table, and Seed Data

on:
  push:
    branches:
      - main

jobs:
  mysql-setup:
    runs-on: ubuntu-latest

    steps:
    # 1. Klono repo-n e projektit
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Përditëso Ubuntu dhe instalo MySQL
    - name: Install MySQL
      run: |
        sudo apt update -y
        sudo apt upgrade -y
        sudo apt install -y mysql-server mysql-client
        sudo systemctl start mysql
        sudo systemctl enable mysql

    # 3. Krijo bazën e të dhënave 'employees'
    - name: Create Database
      run: |
        sudo mysql -e "CREATE DATABASE IF NOT EXISTS employees;"

    # 4. Ekzekuto skriptin për krijimin e tabelës (01-create-table.sql)
    - name: Create Table
      run: |
        sudo mysql -u root -p'Moseprek12@' employees < ./01-create-table.sql

    # 5. Ekzekuto skriptin për futjen e të dhënave (02-seed-data.sql)
    - name: Seed Data
      run: |
        sudo mysql -u root -p'Moseprek12@' employees < ./02-seed-data.sql

    # 6. Verifikimi i të dhënave
    - name: Verify Data in Table
      run: |
        sudo mysql -u root -p'Moseprek12@' -e "USE employees; SELECT * FROM employees;"
