name: MySQL Setup - Create Database and Table

on:
  push:
    branches:
      - main

jobs:
  mysql-setup:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Install MySQL
    - name: Install MySQL
      run: |
        sudo apt update -y
        sudo apt install -y mysql-server mysql-client
        sudo systemctl start mysql
        sudo systemctl enable mysql

    # 3. Create the 'employees' database and use it
    - name: Create Database and Use It
      run: |
        sudo mysql -u root -p'Moseprek12@' -e "CREATE DATABASE employees;"
        sudo mysql -u root -p'Moseprek12@' -e "USE employees;"

    # 4. Create the 'employees' table using the SQL file
    - name: Create Table from SQL File
      run: |
        sudo mysql -u root -p'Moseprek12@' employees < ./01-create-table.sql

    # 5. Seed Data (Insert data into the employees table using SQL file)
    - name: Seed Data from SQL File
      run: |
        sudo mysql -u root -p'Moseprek12@' employees < ./02-seed-data.sql
