name: MySQL Database Setup

on:
  push:
    branches:
      - main

jobs:
  setup-mysql:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          MYSQL_DATABASE: my_database
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -p${{ secrets.SQL_PASSWORD }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install MySQL Client
        run: sudo apt-get install -y mysql-client

      - name: Wait for MySQL to be ready
        run: |
          for i in {60..0}; do
            if mysqladmin ping -h 127.0.0.1 -u root -p${{ secrets.SQL_PASSWORD }} --silent; then
              break
            fi
            echo 'Waiting for MySQL...'
            sleep 5  # Prit më shumë
          done

      - name: Run SQL Scripts
        run: |
          mysql -h 127.0.0.1 -u root -p${{ secrets.SQL_PASSWORD }} my_database < 01-create-table.sql
          mysql -h 127.0.0.1 -u root -p${{ secrets.SQL_PASSWORD }} my_database < 02-seed-data.sql

      - name: Verify Data
        run: |
          mysql -h 127.0.0.1 -u root -p${{ secrets.SQL_PASSWORD }} -e "USE my_database; SELECT * FROM employees;"
