name: MySQL Database Setup

on:
  push:
    branches:
      - main

jobs:
  setup-mysql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install MySQL
      run: |
        sudo apt update
        sudo apt install -y mysql-server

    - name: Start MySQL Service
      run: |
        sudo systemctl start mysql
        sudo systemctl enable mysql

    - name: Create MySQL Database
      run: |
        sudo mysql -u root -e "CREATE DATABASE employees;"

    - name: Create Table in the Database
      run: |
        sudo mysql -u root employees < 01-create-table.sql

    - name: Seed Data into the Database
      run: |
        sudo mysql -u root employees < 02-seed-data.sql
