name: MySQL Database Setup and Seed Data

on:
  push:
    branches:
      - main

jobs:
  mysql-setup:
    runs-on: ubuntu-latest

    steps:
    # 1. Klono repo-n e projektit
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Përditëso Ubuntu dhe instalo MySQL
    - name: Update Ubuntu and Install MySQL
      run: |
        sudo apt update -y
        sudo apt upgrade -y
        sudo apt install -y mysql-server mysql-client
        sudo systemctl start mysql
        sudo systemctl enable mysql

    # 3. Krijo dhe inicializo bazën e të dhënave me skedarët SQL
    - name: Create and Seed Database
      run: |
        sudo mysql -u root -p${{ secrets.MYSQL_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS my_database;"
        sudo mysql -u root -p${{ secrets.MYSQL_PASSWORD }} my_database < ./01-create-table.sql
        sudo mysql -u root -p${{ secrets.MYSQL_PASSWORD }} my_database < ./02-seed-data.sql

    # 4. Verifiko që të dhënat janë futur në tabelë
    - name: Verify Database Setup
      run: |
        sudo mysql -u root -p${{ secrets.MYSQL_PASSWORD }} -e "USE my_database; SELECT * FROM employees;"
