name: MySQL Setup and Seed Data

on:
  push:
    branches:
      - main

jobs:
  mysql-setup:
    runs-on: ubuntu-latest

    steps:
    # 1. Klono repo-n e projektit
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Përditëso Ubuntu dhe instalo MySQL
    - name: Update Ubuntu and Install MySQL
      run: |
        sudo apt update -y
        sudo apt upgrade -y
        sudo apt install -y mysql-server mysql-client
        sudo systemctl start mysql
        sudo systemctl enable mysql

    # 3. Krijo një përdorues të ri MySQL dhe vendos fjalëkalimin
    - name: Create MySQL User and Set Password
      run: |
        sudo mysql -e "CREATE USER 'githubuser'@'localhost' IDENTIFIED BY 'Moseprek12@';"
        sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'githubuser'@'localhost' WITH GRANT OPTION;"
        sudo mysql -e "FLUSH PRIVILEGES;"

    # 4. Krijo bazën e të dhënave
    - name: Create Database
      run: |
        sudo mysql -u githubuser -p'Moseprek12@' -e "CREATE DATABASE IF NOT EXISTS my_database;"

    # 5. Ekzekuto SQL skriptet për krijimin e tabelave dhe futjen e të dhënave
    - name: Execute SQL Scripts
      run: |
        sudo mysql -u githubuser -p'Moseprek12@' my_database < ./01-create-table.sql
        sudo mysql -u githubuser -p'Moseprek12@' my_database < ./02-seed-data.sql

    # 6. Verifikimi i të dhënave
    - name: Verify Database Setup
      run: |
        sudo mysql -u githubuser -p'Moseprek12@' -e "USE my_database; SELECT * FROM employees;"
