name: MySQL Database Creation

on:
  push:
    branches:
      - main

jobs:
  setup-mysql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install MySQL
      run: |
        sudo apt update
        sudo apt install -y mysql-server

    - name: Start MySQL service
      run: |
        sudo systemctl start mysql

    - name: Create MySQL Database
      run: |
        CREATE DATABASE employees;

    - name: Create table in the database
      run: |
        sudo mysql -u root -e
        USE employees; CREATE TABLE IF NOT EXISTS employees (
          id INT AUTO_INCREMENT PRIMARY KEY,
          name VARCHAR(100),
          role VARCHAR(50),
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

    - name: Seed data into the database
      run: |
        sudo mysql -u root -e "USE employees; INSERT INTO employees (name, role) VALUES
        ('Altin', 'DevOps Engineer'),
        ('Enis', 'Developer');"

    - name: Stop MySQL service
      run: |
        sudo systemctl stop mysql
