name: MySQL Setup - Create Database, Table, and Seed Data

on:
  push:
    branches:
      - main

jobs:
  mysql-setup:
    runs-on: ubuntu-latest

    steps:
    # 1. Klono repo-n e projektit
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Instaloni MySQL
    - name: Install MySQL
      run: |
        sudo apt update -y
        sudo apt install -y mysql-server mysql-client
        sudo systemctl start mysql
        sudo systemctl enable mysql

    # 3. Krijoni bazën 'employees' (pa kontrolluar nëse ekziston)
    - name: Create Database
      run: |
        sudo mysql -e "CREATE DATABASE employees;"

    # 4. Krijoni tabelën 'employees'
    - name: Create Table
      run: |
        sudo mysql -u root -p'Moseprek12@' employees < ./01-create-table.sql

    # 5. Fut të dhënat në tabelën 'employees'
    - name: Seed Data
      run: |
        sudo mysql -u root -p'Moseprek12@' employees < ./02-seed-data.sql
